version: '3'

services:
  api:
      build:
        dockerfile: Dockerfile
      container_name: whatsapp_front
      restart: always
      ports:
        - '3030:3030'
      volumes:
        - .:/usr/src/app