version: '3'

services:
  db:
    platform: linux/x86_64
    image: postgres
    restart: always
    container_name: postgres_whatsapp_bot
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mydb
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_PASSWORD: "123456"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis:/var/lib/redis
  backend:
    build:
      dockerfile: Dev.Dockerfile
    container_name: whatsapp_bot
    restart: always
    depends_on:
      - db-mysql
    ports:
      - '${PORT}:8080'
    volumes:
      - .:/usr/src/app

volumes:
  db:
  backend:
  redis-stack:
