version: '3'

services:
  db-pg:
    platform: linux/x86_64
    image: postgres
    restart: always
    container_name: postgres_whatsapp_bot
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    # networks:
    #   - whatsapp_back_network
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_PASSWORD: "123456"
    ports:
      - "6379:6379"
      - "8001:8001"
    # volumes:
    #   - redis:/var/lib/redis
    # networks:
    #   - whatsapp_back_network
  backend:
    build:
      dockerfile: Dev.Dockerfile
    container_name: whatsapp_bot
    restart: always
    environment:
      DB_HOST: db-pg
    depends_on:
      - db-pg
    ports:
      - '${PORT}:8080'
    volumes:
      - .:/usr/src/app
    # networks:
    #   - whatsapp_back_network
  # frontend:
  #   build:
  #     context: ../frontend/.
  #     dockerfile: ../frontend/Dockerfile
  #   container_name: whatsapp_bot_front
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ../frontend/.:/usr/src/app
    # networks:
    #   - whatsapp_back_network
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - ./data/public:/var/www/public
  #   depends_on:
  #     - backend
  #   networks:
  #     - whatsapp_back_network

# networks:
#   whatsapp_back_network:
#     driver: bridge

# volumes:
#   db-pg:
  # backend:
  # redis:
  # nginx:
