version: "3"

services:
  db-pg:
    platform: linux/x86_64
    image: postgres
    restart: always
    container_name: falatu-db-new
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdataft:/var/lib/postgresql/data
    networks:
      - db_pg_network-ft
  redis-stack:
    image: redis/redis-stack:latest
    container_name: falatu-redis-new
    restart: always
    environment:
      REDIS_PASSWORD: "123456"
    ports:
      - "6380:6379"
    volumes:
      - redisft:/var/lib/redis
    networks:
      - proxy_manager
  backend:
    build:
      context: .
      dockerfile: Prod.Dockerfile
      args:
        - PORT=$PORT
    container_name: falatu-back-new
    restart: always
    environment:
      DB_HOST: db-pg
      DB_PORT: 5432
      REDIS_URI: redis://redis-stack:6379
      TZ: America/Sao_Paulo
    depends_on:
      - db-pg
      - redis-stack
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/public
    networks:
      - db_pg_network-ft
      - proxy_manager
  frontend:
    build:
      context: ../frontend/.
      dockerfile: Prod.Dockerfile
    container_name: falatu-front-new
    restart: always
    depends_on:
      - backend
    environment:
      TZ: America/Sao_Paulo
    # ports:
    #   - "3334:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - proxy_manager
    stdin_open: true
    tty: true
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdataft:
    name: pgdata-ft
  redisft:
    name: redis-ft

networks:
  db_pg_network-ft:
    name: db_pg_network-ft
  proxy_manager:
    name: proxy_manager
