version: '3'

services:
  db-pg:
    platform: linux/x86_64
    image: postgres
    restart: always
    container_name: postgres_whatsapp_bot
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_PASSWORD: "123456"
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
  backend:
    build:
      dockerfile: Dev.Dockerfile
    container_name: bot_backend
    restart: always
    environment:
      DB_HOST: db-pg
    depends_on:
      - db-pg
    ports:
      - '${PORT}:8080'
    volumes:
      - .:/usr/src/app
  frontend:
    build:
      context: ../front/.
      dockerfile: ../front/Dockerfile
    container_name: bot_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ../front/.:/usr/src/app
    stdin_open: true
    tty: true

volumes:
  pgdata:
    name: pgdata
  backend:
    name: backend
  redis:
    name: redis
